Changed usages of modals
superdesk/superdesk-client-core pull request #4259
Opened 2023-05-31 11:07 UTC by dzonidoo

SDESK-6875

2023-05-31 12:08 UTC, thecalcc commented
Check flex div usage in `UploadAttachmentsModal` and if we can replace it and use Spacer from ui-framework.
Go through Modal changes which you are not 100% confident about and re-verify them in the UI. 
In `ModalPropmt.tsx` type the state as you have done with props.

2023-05-31 12:09 UTC, thecalcc commented
Make sure to resolve all the conflicts before requesting a new review.

2023-06-02 11:28 UTC, tomaskikutis approved these changes
before merging we'll need to go over usages which you told me @dzonidoo you couldn't check - like imatrics widget extension

2023-06-02 11:28 UTC, tomaskikutis commented on scripts/apps/authoring/attachments/UploadAttachmentsModal.tsx
> +                onHide={this.state.saving ? null : this.props.closeModal}
According to the interface, `onHide` is a mandatory function. So if we want to work around this, we should pass a function that is not doing anything(like `noop` from lodash) - and not `null`.

2023-06-02 11:28 UTC, tomaskikutis commented on scripts/apps/authoring/attachments/UploadAttachmentsModal.tsx
> +                            style={{
It looks like it would be possible to use a spacer here?

2023-06-26 11:04 UTC, tomaskikutis commented
address last comments, ensure typescript part of lint passes ; we'll still have to wait for Konstantin to fix lint so CI of this PR passes as well

2023-07-03 16:03 UTC, tomaskikutis commented
`CI / test` has to pass

2023-07-11 10:16 UTC, tomaskikutis approved these changes

2023-07-13 13:15 UTC, tomaskikutis requested changes
Let's wait until 2.7 is released and only merge it afterwards

2023-07-13 13:16 UTC, tomaskikutis approved these changes
My bad, I forgot again that this is going to be merged to post big merge, not develop. We can merge it as soon as tests pass

2023-07-13 14:31 UTC, tomaskikutis approved these changes

2023-07-13 14:38 UTC, merged