Event and Planning profile editor doesn't display Groups in Fields
superdesk/superdesk-client-core pull request #4620
Opened 2024-09-04 12:36 UTC by dzonidoo

STT-74

2024-09-04 12:45 UTC, tomaskikutis approved these changes

2024-09-04 12:48 UTC, tomaskikutis requested changes
I take back my approval :D Why is planning-related code added to client-core rather than planning?

Could you explain what is causing the issue?

2024-09-04 14:11 UTC, dzonidoo commented
i can show u...

2024-09-09 14:04 UTC, closed without merging

2024-09-09 14:07 UTC, dzonidoo commented
We are closing this pull request because the CSS code is specific to Planning and should be added to planning repo...